### ISSUE TITLE
Proxy links

### ISSUE THREAD

**Issue by xhz8s** [singhkumarpratik/TMDB-Torrent-Movie-Database#1]
Many ISP's block Piratebay, therefore it would be nice to fetch proxy links from sites like [proxybay.gdn](https://proxybay.gdn/) and use these instead. String parsing should'nt be a problem

**Comment by duckyb** [comment]
And how would you know which url to use?

**Comment by brian6932** [comment]
Can you add an option to use native urls and have proxy urls by default? I have userstyles and extensions for both RARBG and TPB that are really useful
